### PR TITLE
Simplify Windows instructions

### PR DESCRIPTION
**Pull request by nazar-pc**
With latest changes in mediasoup configuration step is not needed, so this should be merged once new release is out

### CODE REVIEW

**Review by ibc — APPROVED** [review]
Amazing

**Comment by nazar-pc** [comment]
I see this went onto website, will you do TypeScript release today? These changes are meant to go in conjunction with changes that are currently unreleased in `v3` branch.

**Comment by ibc** [comment]
Yes, I'll do it soon today.

**Comment by information-security** [comment]
Hi,

First of all, I'd like to thank you all for the great work that you have done. I really appreciate the effort that you have put on this project.

Secondly, I think the installation page still needs some refactoring. I am not sure if I followed the instructions correctly but it was unclear to me that what should I do after installing `Microsoft Visual Studio environment with MSVC compiler (with C++11 support)`. I had many hours of headache to get the mediasoup build to work while I definitely had everything installed. In the end, I followed these instructions to get it to work:

1. Opened a CMD
2. Manually ran `vcvars64.bat`
3. `npm i`

As simple as that but it took me almost one day to figure it out. I am not sure if we need to run `vcvars64.bat` manually at all but it was the only way I could successfully install mediasoup. BTW, it took me many hours before I found out that the `PowerShell` is not an option here and I have to go with `CMD` if I want the MSVC environment to be setup correctly.

For these reasons, I think it is better to provide more details on the installation page in order to clarify the exact instructions required to get the environment ready.

Please let me know if you think I should submit an issue for this.

Thanks again

**Comment by nazar-pc** [comment]
@information-security with very latest mediasoup release and modern MSVS (I used 2019) it should not require any extra work. Instructions removed by this PR had examples for PowerShell too, it was a bit more involved, but worked jist fine, but none of that is necessary anymore.

If you have further questions or comments, please create a thread on the forum.

**Comment by information-security** [comment]
Dear @nazar-pc,

Thank you for your great work of replacing the old and deprecated build system with mason. Nice job. I am personally very thankful. I wish one day I can pay my debt by contributing to this great project.

> If you have further questions or comments, please create a thread on the forum.

Please note that, I am not trying to get help here as I could workaround the issue by manually issuing commands in the above post. However, I still think that the installation page and/or script need some improvements. That's why I used your issue tracker instead of public forums to let you guys know that something is wrong.
Honestly, I rummaged through the forum before I posted here. It seems that other ppl are also confused regarding the steps required to prepare the requirements (e.g. [here](https://mediasoup.discourse.group/t/mediasoup-installation-error-in-windows-10-in-vscode-react-project/3452/25), [here](https://mediasoup.discourse.group/t/i-had-a-error-while-exec-npm-install-at-windows-os-help-please/3503/9), and [here](https://mediasoup.discourse.group/t/meson-build0-error-unknown-compiler-s/3492)). They had to manually run the `vcvars64.bat` to workaround the issues.(e.g. [here](https://mediasoup.discourse.group/t/mediasoup-installation-error-in-windows-10-in-vscode-react-project/3452/31)). And obviously many of them had to do some [manual tweaks](https://mediasoup.discourse.group/t/mediasoup-installation-error-in-windows-10-in-vscode-react-project/3452/16) to get things to work like what I did. These might be for your previous releases but with the latest release the problem still persists.


> with very latest mediasoup release and modern MSVS (I used 2019) it should not require any extra work.

I already had the latest mediasoup release and MSVC 2019 installed but again it is not automatically working.


> Instructions removed by this PR had examples for PowerShell too, it was a bit more involved, but worked jist fine, but none of that is necessary anymore.

Trust me, it is not working as you expect it to work. At least not on our systems. I had to run `vcvars64.bat` manually and this enforces me to use only CMD as this `bat` file does not work in PowerShell.

One thing to note is that I didn't want to install by `npm i mediasoup`, instead, I cloned the head of the repo and issued `npm i` inside its root directory. I assume the installation requirements must be the same. Are you sure that you don't have any specific configurations (such as a modification of PATH environment variable) in your system that is making a difference between your tests and our clean installations?
I had the following paths concatenated in the PATH variable:
`C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin`
`C:\Python39`
`C:\Python39\Scripts`
`C:\Program Files\node-v16.6.1-win-x64`

Also I added `C:\MinGW\msys\1.0\bin` as per new requirements at the end of the paths list but these were not sufficient to have the installation script run successfully.

Adding following paths did not help either:
`C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin`
`C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\`

While having all these paths and configurations already setup on my system, the installation script does not work. While issuing `vcvars64.bat && npm i` works flawlessly. This tells me that although all the requirements are installed the script does not work as expected.

**Comment by information-security** [comment]
I didn't quite get the reason for your thumbs down without any explanation considering that you seem to [already know that something is wrong with the current installation script](https://github.com/versatica/mediasoup/issues/701)!

**Comment by nazar-pc** [comment]
As I already said:
> If you have further questions or comments, please create a thread on the forum.

Yet you continue posting huge comments with a bunch of info in this thread :disappointed:

**Pull request merged**
